resolver: lts-13.20

packages:
- coinmetrics
- coinmetrics-all-blockchains
- coinmetrics-binance
- coinmetrics-bitcoin
- coinmetrics-cardano
- coinmetrics-eos
- coinmetrics-ethereum
- coinmetrics-export
- coinmetrics-grin
- coinmetrics-iota
- coinmetrics-monero
- coinmetrics-monitor
- coinmetrics-nem
- coinmetrics-neo
- coinmetrics-ripple
- coinmetrics-stellar
- coinmetrics-storage
- coinmetrics-tendermint
- coinmetrics-tezos
- coinmetrics-tron
- coinmetrics-waves

extra-deps:
- diskhash-0.0.4.0
- git: https://github.com/quyse/hanalytics.git
  commit: 01e7a68d35b45359aeb7b7f700eab5c4b9cc908b
  subdirs:
  - hanalytics-avro
  - hanalytics-base
  - hanalytics-bigquery
  - hanalytics-postgres
